# Form implementation generated from reading ui file 'UI\EdgeDectetion.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EdgeDetectionForm(object):
    def setupUi(self, EdgeDetectionForm):
        EdgeDetectionForm.setObjectName("EdgeDetectionForm")
        EdgeDetectionForm.resize(766, 578)
        self.label = QtWidgets.QLabel(parent=EdgeDetectionForm)
        self.label.setGeometry(QtCore.QRect(230, 10, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=EdgeDetectionForm)
        self.groupBox.setGeometry(QtCore.QRect(59, 69, 661, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.btn_Sobel = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_Sobel.setGeometry(QtCore.QRect(20, 20, 121, 51))
        self.btn_Sobel.setObjectName("btn_Sobel")
        self.btn_Canny = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_Canny.setGeometry(QtCore.QRect(270, 20, 131, 51))
        self.btn_Canny.setObjectName("btn_Canny")
        self.btn_Hybrid = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_Hybrid.setGeometry(QtCore.QRect(510, 20, 121, 51))
        self.btn_Hybrid.setObjectName("btn_Hybrid")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=EdgeDetectionForm)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 170, 661, 411))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_Select = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btn_Select.setGeometry(QtCore.QRect(80, 340, 191, 51))
        self.btn_Select.setObjectName("btn_Select")
        self.label_Input = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_Input.setGeometry(QtCore.QRect(20, 30, 300, 300))
        self.label_Input.setStyleSheet("border: 2px solid gray; background-color: white;")
        self.label_Input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Input.setObjectName("label_Input")
        self.label_Output = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_Output.setGeometry(QtCore.QRect(350, 30, 301, 300))
        self.label_Output.setStyleSheet("border: 2px solid gray; background-color: white;")
        self.label_Output.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Output.setObjectName("label_Output")

        self.retranslateUi(EdgeDetectionForm)
        QtCore.QMetaObject.connectSlotsByName(EdgeDetectionForm)

    def retranslateUi(self, EdgeDetectionForm):
        _translate = QtCore.QCoreApplication.translate
        EdgeDetectionForm.setWindowTitle(_translate("EdgeDetectionForm", "Edge Detection App"))
        self.label.setText(_translate("EdgeDetectionForm", "ỨNG DỤNG ẨN GIẤU THÔNG TIN"))
        self.groupBox.setTitle(_translate("EdgeDetectionForm", "Các thuật toán phát hiện cạnh"))
        self.btn_Sobel.setText(_translate("EdgeDetectionForm", "Sobel"))
        self.btn_Canny.setText(_translate("EdgeDetectionForm", "Canny"))
        self.btn_Hybrid.setText(_translate("EdgeDetectionForm", "Hybrid"))
        self.groupBox_2.setTitle(_translate("EdgeDetectionForm", "Phát hiện cạnh"))
        self.btn_Select.setText(_translate("EdgeDetectionForm", "Chọn ảnh"))
        self.label_Input.setText(_translate("EdgeDetectionForm", "Ảnh gốc"))
        self.label_Output.setText(_translate("EdgeDetectionForm", "Ảnh sau phát hiện cạnh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EdgeDetectionForm = QtWidgets.QWidget()
    ui = Ui_EdgeDetectionForm()
    ui.setupUi(EdgeDetectionForm)
    EdgeDetectionForm.show()
    sys.exit(app.exec())
