# Form implementation generated from reading ui file 'D:\Project DoAn (Version2)\UI\FormExtract.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExtractForm(object):
    def setupUi(self, ExtractForm):
        ExtractForm.setObjectName("ExtractForm")
        ExtractForm.resize(780, 640)
        self.label_Title = QtWidgets.QLabel(parent=ExtractForm)
        self.label_Title.setGeometry(QtCore.QRect(199, 10, 411, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.groupBox_Algo = QtWidgets.QGroupBox(parent=ExtractForm)
        self.groupBox_Algo.setGeometry(QtCore.QRect(60, 60, 660, 80))
        self.groupBox_Algo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_Algo.setObjectName("groupBox_Algo")
        self.btn_Sobel = QtWidgets.QPushButton(parent=self.groupBox_Algo)
        self.btn_Sobel.setGeometry(QtCore.QRect(20, 25, 120, 40))
        self.btn_Sobel.setObjectName("btn_Sobel")
        self.btn_Canny = QtWidgets.QPushButton(parent=self.groupBox_Algo)
        self.btn_Canny.setGeometry(QtCore.QRect(260, 25, 120, 40))
        self.btn_Canny.setObjectName("btn_Canny")
        self.btn_Hybrid = QtWidgets.QPushButton(parent=self.groupBox_Algo)
        self.btn_Hybrid.setGeometry(QtCore.QRect(500, 25, 120, 40))
        self.btn_Hybrid.setObjectName("btn_Hybrid")
        self.groupBox_Extract = QtWidgets.QGroupBox(parent=ExtractForm)
        self.groupBox_Extract.setGeometry(QtCore.QRect(60, 160, 660, 420))
        self.groupBox_Extract.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_Extract.setObjectName("groupBox_Extract")
        self.btn_SelectStegoImage = QtWidgets.QPushButton(parent=self.groupBox_Extract)
        self.btn_SelectStegoImage.setGeometry(QtCore.QRect(90, 330, 120, 30))
        self.btn_SelectStegoImage.setObjectName("btn_SelectStegoImage")
        self.label_Input = QtWidgets.QLabel(parent=self.groupBox_Extract)
        self.label_Input.setGeometry(QtCore.QRect(30, 40, 280, 260))
        self.label_Input.setStyleSheet("border: 2px solid gray; background-color: white;")
        self.label_Input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Input.setObjectName("label_Input")
        self.label_Edge = QtWidgets.QLabel(parent=self.groupBox_Extract)
        self.label_Edge.setGeometry(QtCore.QRect(360, 40, 280, 260))
        self.label_Edge.setStyleSheet("border: 2px solid gray; background-color: white;")
        self.label_Edge.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Edge.setObjectName("label_Edge")
        self.btn_Extract = QtWidgets.QPushButton(parent=self.groupBox_Extract)
        self.btn_Extract.setGeometry(QtCore.QRect(429, 329, 161, 31))
        self.btn_Extract.setObjectName("btn_Extract")

        self.retranslateUi(ExtractForm)
        QtCore.QMetaObject.connectSlotsByName(ExtractForm)

    def retranslateUi(self, ExtractForm):
        _translate = QtCore.QCoreApplication.translate
        ExtractForm.setWindowTitle(_translate("ExtractForm", "Giải mã / Trích xuất tin"))
        self.label_Title.setText(_translate("ExtractForm", "ỨNG DỤNG ẨN GIẤU THÔNG TIN"))
        self.groupBox_Algo.setTitle(_translate("ExtractForm", "Chọn thuật toán phát hiện cạnh"))
        self.btn_Sobel.setText(_translate("ExtractForm", "Sobel"))
        self.btn_Canny.setText(_translate("ExtractForm", "Canny"))
        self.btn_Hybrid.setText(_translate("ExtractForm", "Hybrid"))
        self.groupBox_Extract.setTitle(_translate("ExtractForm", "Trích xuất thông tin từ ảnh"))
        self.btn_SelectStegoImage.setText(_translate("ExtractForm", "Chọn ảnh"))
        self.label_Input.setText(_translate("ExtractForm", "Ảnh nhúng"))
        self.label_Edge.setText(_translate("ExtractForm", "Thông điệp trích xuất"))
        self.btn_Extract.setText(_translate("ExtractForm", "Trích xuất tin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExtractForm = QtWidgets.QWidget()
    ui = Ui_ExtractForm()
    ui.setupUi(ExtractForm)
    ExtractForm.show()
    sys.exit(app.exec())
