# Form implementation generated from reading ui file 'UI/formlogin.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(966, 583)
        Form.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(260, 120, 491, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.lb_account = QtWidgets.QLabel(parent=Form)
        self.lb_account.setGeometry(QtCore.QRect(180, 230, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.lb_account.setFont(font)
        self.lb_account.setObjectName("lb_account")
        self.lb_account_2 = QtWidgets.QLabel(parent=Form)
        self.lb_account_2.setGeometry(QtCore.QRect(180, 290, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.lb_account_2.setFont(font)
        self.lb_account_2.setObjectName("lb_account_2")
        self.btnLogin = QtWidgets.QPushButton(parent=Form)
        self.btnLogin.setGeometry(QtCore.QRect(280, 380, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btnLogin.setFont(font)
        self.btnLogin.setAutoFillBackground(False)
        self.btnLogin.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 127);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(50, 110, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(100, 170, 255);\n"
"}")
        icon = QtGui.QIcon.fromTheme("address-book-new")
        self.btnLogin.setIcon(icon)
        self.btnLogin.setObjectName("btnLogin")
        self.btn_Exit = QtWidgets.QPushButton(parent=Form)
        self.btn_Exit.setGeometry(QtCore.QRect(640, 380, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_Exit.setFont(font)
        self.btn_Exit.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 127);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(50, 110, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(100, 170, 255);\n"
"}")
        self.btn_Exit.setObjectName("btn_Exit")
        self.btn_Register = QtWidgets.QPushButton(parent=Form)
        self.btn_Register.setGeometry(QtCore.QRect(460, 380, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.btn_Register.setFont(font)
        self.btn_Register.setAutoFillBackground(False)
        self.btn_Register.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 127);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(50, 110, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(100, 170, 255);\n"
"}")
        self.btn_Register.setObjectName("btn_Register")
        self.txbAccount = QtWidgets.QLineEdit(parent=Form)
        self.txbAccount.setGeometry(QtCore.QRect(360, 240, 401, 41))
        self.txbAccount.setObjectName("txbAccount")
        self.txbPassword = QtWidgets.QLineEdit(parent=Form)
        self.txbPassword.setGeometry(QtCore.QRect(360, 300, 401, 41))
        self.txbPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txbPassword.setObjectName("txbPassword")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Ứng Dụng Ẩn Giấu Thông Tin"))
        self.lb_account.setText(_translate("Form", "Tài khoản :"))
        self.lb_account_2.setText(_translate("Form", "Mật khẩu :"))
        self.btnLogin.setText(_translate("Form", "Đăng nhập"))
        self.btn_Exit.setText(_translate("Form", "Thoát"))
        self.btn_Register.setText(_translate("Form", "Đăng Ký"))
        self.txbAccount.setPlaceholderText(_translate("Form", "Enter UserAccount"))
        self.txbPassword.setPlaceholderText(_translate("Form", "Enter UserPassword"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
