# Form implementation generated from reading ui file 'ui/form_Register.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(170, 30, 561, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(70, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(20, 250, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txb_accountname = QtWidgets.QLineEdit(parent=Form)
        self.txb_accountname.setGeometry(QtCore.QRect(240, 150, 371, 31))
        self.txb_accountname.setObjectName("txb_accountname")
        self.txb_Password1 = QtWidgets.QLineEdit(parent=Form)
        self.txb_Password1.setGeometry(QtCore.QRect(240, 200, 371, 31))
        self.txb_Password1.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txb_Password1.setObjectName("txb_Password1")
        self.txb_Password2 = QtWidgets.QLineEdit(parent=Form)
        self.txb_Password2.setGeometry(QtCore.QRect(240, 250, 371, 31))
        self.txb_Password2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txb_Password2.setObjectName("txb_Password2")
        self.btn_RegisterConfirm = QtWidgets.QPushButton(parent=Form)
        self.btn_RegisterConfirm.setGeometry(QtCore.QRect(200, 330, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.btn_RegisterConfirm.setFont(font)
        self.btn_RegisterConfirm.setAutoFillBackground(False)
        self.btn_RegisterConfirm.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 127);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(50, 110, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(100, 170, 255);\n"
"}")
        self.btn_RegisterConfirm.setObjectName("btn_RegisterConfirm")
        self.btn_ExitRegister = QtWidgets.QPushButton(parent=Form)
        self.btn_ExitRegister.setGeometry(QtCore.QRect(420, 330, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.btn_ExitRegister.setFont(font)
        self.btn_ExitRegister.setAutoFillBackground(False)
        self.btn_ExitRegister.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 127);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(50, 110, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(100, 170, 255);\n"
"}")
        self.btn_ExitRegister.setObjectName("btn_ExitRegister")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(650, 150, 321, 216))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("ui\\../../../../Dowload/quan-ly-tai-lieu-1 (1) (1).jpg"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(820, 0, 111, 111))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("ui\\../../../../Dowload/icons8-register-100.png"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(72, 419, 861, 124))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("ui\\../../../../Dowload/—Pngtree—blue curve line curve wavy_3812468 (1).png"))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Đăng ký tài khoản của bạn"))
        self.label_2.setText(_translate("Form", "Tài khoản:"))
        self.label_3.setText(_translate("Form", "Mật khẩu:"))
        self.label_4.setText(_translate("Form", "Nhập lại mật khẩu:"))
        self.txb_accountname.setPlaceholderText(_translate("Form", "Enter useraccount"))
        self.txb_Password1.setPlaceholderText(_translate("Form", "Enter password"))
        self.txb_Password2.setPlaceholderText(_translate("Form", "Enter password again"))
        self.btn_RegisterConfirm.setText(_translate("Form", "Đăng ký"))
        self.btn_ExitRegister.setText(_translate("Form", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
