# Form implementation generated from reading ui file 'UI/Menu_User.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1071, 555)
        Form.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.lb_TypeAccount = QtWidgets.QLabel(parent=Form)
        self.lb_TypeAccount.setGeometry(QtCore.QRect(680, 30, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lb_TypeAccount.setFont(font)
        self.lb_TypeAccount.setStyleSheet("\n"
"color:rgb(0, 0, 0)")
        self.lb_TypeAccount.setObjectName("lb_TypeAccount")
        self.btn_SearchingMenu = QtWidgets.QPushButton(parent=Form)
        self.btn_SearchingMenu.setGeometry(QtCore.QRect(270, 260, 171, 61))
        self.btn_SearchingMenu.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 0);")
        self.btn_SearchingMenu.setObjectName("btn_SearchingMenu")
        self.btn_ManageDocumentMenu = QtWidgets.QPushButton(parent=Form)
        self.btn_ManageDocumentMenu.setGeometry(QtCore.QRect(50, 260, 171, 61))
        self.btn_ManageDocumentMenu.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 0);")
        self.btn_ManageDocumentMenu.setObjectName("btn_ManageDocumentMenu")
        self.label_nameapp = QtWidgets.QLabel(parent=Form)
        self.label_nameapp.setGeometry(QtCore.QRect(190, 140, 621, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.label_nameapp.setFont(font)
        self.label_nameapp.setStyleSheet("font: 700 28pt \"Segoe UI\";\n"
"color:rgb(0, 0, 0);")
        self.label_nameapp.setObjectName("label_nameapp")
        self.btn_exit = QtWidgets.QPushButton(parent=Form)
        self.btn_exit.setGeometry(QtCore.QRect(690, 260, 171, 61))
        self.btn_exit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);")
        self.btn_exit.setObjectName("btn_exit")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(300, 340, 111, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\Project DoAn (Version2)\ImageForGui\icons8-encrypt-100.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(100, 340, 151, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\Project DoAn (Version2)\ImageForGui\document.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(730, 340, 121, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\Project DoAn (Version2)\ImageForGui\icons8-exit-96.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(430, 20, 101, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\Project DoAn (Version2)\ImageForGui\icons8-home-120.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(850, 10, 61, 91))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\Project DoAn (Version2)\ImageForGui\icons8-account-50.png"))
        self.label_5.setObjectName("label_5")
        self.btn_ExtractMenu = QtWidgets.QPushButton(parent=Form)
        self.btn_ExtractMenu.setGeometry(QtCore.QRect(490, 260, 161, 61))
        self.btn_ExtractMenu.setStyleSheet("background-color: rgb(255, 170, 0); color: rgb(0, 0, 0);")
        self.btn_ExtractMenu.setObjectName("btn_ExtractMenu")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(530, 360, 101, 81))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\Project DoAn (Version2)\ImageForGui\Extract-object_35790.png"))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_TypeAccount.setText(_translate("Form", "Tài Khoản: USER"))
        self.btn_SearchingMenu.setText(_translate("Form", "Ẩn mã "))
        self.btn_ManageDocumentMenu.setText(_translate("Form", "Phát hiện cạnh"))
        self.label_nameapp.setText(_translate("Form", "ỨNG DỤNG ẨN GIẤU THÔNG TIN"))
        self.btn_exit.setText(_translate("Form", "Thoát"))
        self.btn_ExtractMenu.setText(_translate("Form", "Trích Xuất"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())


